### PR TITLE
Do not write past buffer in USB_ReadPacket()

### PR DESCRIPTION
**Pull request by desowin**
USB_ReadPacket() copies data in multiple of 4-bytes. This can lead to
writing past the destination buffer if len is not multiple of 4.

The issue was observed in MSC class driver. USBH_MSC_ClassRequest()
passes pointer to MSC_Handler->max_lun as control transfer buffer.
Because max_lun variable is 4 bytes in length, the issue is causing as
severe problems as it could. USB_ReadPacket() correctly wrote the least
significant byte of the max_len but also did write the upper 3 bytes with
unwanted non-zero data. As a result, USB Host did incorrectly set the
max_lun value to MAX_SUPPORTED_LUN (2) and queried non-existed LUNs from
devices with just a single LUN.

Solve the issue by writing the last data word in byte mode if buffer
length is not multiple of 4.

### Contributor License Agreement (CLA)
* The Pull Request feature will be considered by STMicroelectronics only after a **Contributor License Agreement (CLA)** mechanism has been deployed.
* We are currently working on the set-up of this procedure.

### CODE REVIEW

**Comment by ALABSTM** [comment]
Hi Tomasz,

I forwarded your email to @bouattay, from our USB development team. He confirmed the issue you pointed out has already been fixed in the USB Host Library v3.3.3. This latter is available in the [STM32CubeL4](https://github.com/STMicroelectronics/STM32CubeL4) **v1.15.0** which has been published today.

We do hope this new library revision addresses the issue you pointed out. If it is the case, this pull-request could be closed.

We wish you good luck for the project you are working on.

Regarding the pull-requests, we are actively working on the question. We cannot share an official date for the moment and do count on your patience and trust.

In the meanwhile, as we only process issues here at STMicroelectronics, may I suggest you to use special formatting in to emphasize on differences you would like to highlight? Below is how you could do it the *```diff*, *-*, and *+* tags.

Simply click on the "..." in the upper-right corner of this comment and select option "Edit" to see the comment in his raw form and bee able to see how the tags are used.

Please note also that character ` is obtained by pressing "alt gr"+"7" keys simultaneously.

With regards,

```diff
  * @brief  USB_ReadPacket : read a packet from the Tx FIFO associated
  *         with the EP/channel
  * @param  USBx  Selected device
-  * @param  dest  source pointer
+  * @param  dest  destination pointer
  * @param  len  Number of bytes to read
-  * @param  dma USB dma enabled or disabled
-  *          This parameter can be one of these values:
-  *           0 : DMA feature not used
-  *           1 : DMA feature used
  * @retval pointer to destination buffer
  */
```

**Comment by desowin** [comment]
> Hi Tomasz,
> 
> I forwarded your email to @bouattay, from our USB development team. He confirmed the issue you pointed out has already been fixed in the USB Host Library v3.3.3. This latter is available in the [STM32CubeL4](https://github.com/STMicroelectronics/STM32CubeL4) **v1.15.0** which has been published today.
> 
> We do hope this new library revision addresses the issue you pointed out. If it is the case, this pull-request could be closed.

USB Host Library v3.3.3 fixes the max LUN issue by taking only the low 8 bits of the result, effecively not caring about the writes past the buffer size as provided to USB_ReadPacket().

This pull request solves the issue by not allowing the write past buffer in the first place. If ST desires to leave the USB_ReadPacket() as it is, then it would be appreciated if it clearly stated to the users of the library that the library, by design, rounds up the buffer size to 4 and *writes* to such round up size. While this behaviour is no longer causing any problems for MSC with v3.3.3, in my opinion such round-up to multiple of 4 is pretty unexpected for general user.

> In the meanwhile, as we only process issues here at STMicroelectronics, may I suggest you to use special formatting in to emphasize on differences you would like to highlight? Below is how you could do it the _```diff_, _-_, and _+_ tags.

I don't quite understand the reason and/or what you ask for. You can click at the "Commits" [1] and/or "Files changed" [2] to see the proposed changes. Each pull request I have opened, emphasizes on one issue.

[1] https://github.com/STMicroelectronics/STM32CubeF7/pull/10/commits
[2] https://github.com/STMicroelectronics/STM32CubeF7/pull/10/files

**Comment by ALABSTM** [comment]
Hi Tomasz,

I let @bouattay answer you last comment.

With regards,

**Comment by ALABSTM** [comment]
Hi Tomasz,

Please allow me to close this issue as it is solved by the USB Host Library v3.3.3. This latter will be available within the STM32CubeF7 **v1.16.0** which will be released soon on GitHub.

With regards,

**Comment by ALABSTM** [comment]
Hi Tomasz,

The STM32CubeF7 **v1.16.0** has just been released on GitHub.

With regards,

**Pull request closed without merging**
